var homeContent = "<div class='placeHeader'><H1>Home</H1></div><div class='topPara'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta error reprehenderit quisquam quis voluptates laboriosam quidem ab similique delectus a consequatur omnis minus sed, ipsa dignissimos qui culpa ex? Dolorem?</div><div class='mainStuff'><div class='sectOne'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectTwo'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectThree'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectFour'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div></div>";
var placesContent = "<div class='placeHeader'><H1>Places</H1></div><div class='topPara'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta error reprehenderit quisquam quis voluptates laboriosam quidem ab similique delectus a consequatur omnis minus sed, ipsa dignissimos qui culpa ex? Dolorem?</div><div class='placeStuff'><div class='sectOne'><div class='ima'></div><div class='para'><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p></div></div> <div class='sectTwo'><div class='ima'></div><div class='para'>    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p></div></div><div class='sectThree'><div class='ima'></div><div class='para'>    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p></div></div><div class='sectFour'><div class='ima'></div><div class='para'>    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p></div></div></div>";
var citiesContent = " <div class='placeHeader'><H1>Cities</H1></div><div class='topPara'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta error reprehenderit quisquam quis voluptates laboriosam quidem ab similique delectus a consequatur omnis minus sed, ipsa dignissimos qui culpa ex? Dolorem?</div><div class='homeStuff'><div class='sectOne'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectTwo'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectThree'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectFour'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div></div>";
var contactContent = "<div class='placeHeader'><H1>Contact</H1></div><div class='topPara'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta error reprehenderit quisquam quis voluptates laboriosam quidem ab similique delectus a consequatur omnis minus sed, ipsa dignissimos qui culpa ex? Dolorem?</div><div class='contactStuff'><div class='sectOne'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectTwo'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectThree'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div><div class='sectFour'>    <div class='ima'></div>    <div class='para'>        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque vel iure pariatur vero voluptas incidunt mollitia voluptates iusto nostrum repellat odit fugiat quia eum, dolor saepe quam nulla! Corrupti, dolor.</p>    </div></div></div>";

function init() {
    // console.log("Init Here")
    $("nav a").click(function(event){
        let buttonId = this.id;
        let contentID = buttonId + "Content";
        console.log(buttonId);

        $("#hello").html(eval(contentID));
    });

    
}

$(document).ready(function() {
    init();
})